this.manifest = {
  name: 'Japanese Memrise Enhancements',
  settings: [
    {
      tab: i18n.get('Learning / Reviewing'),
      group: i18n.get('Prompts'),
      name: 'replaceKanaMultipleChoiceWithTyping',
      type: 'checkbox',
      label: i18n.get('Replace kana multiple choice with typing'),
    },
    {
      tab: i18n.get('Learning / Reviewing'),
      group: i18n.get('Timer'),
      name: 'customThings',
      type: 'customThingsTable',
    },
    {
      tab: i18n.get('Learning / Reviewing'),
      group: i18n.get('Prompts'),
      name: 'replaceKanjiTypingWithMultipleChoice',
      type: 'checkbox',
      label: i18n.get('Replace kanji typing with multiple choice'),
    },
    {
      tab: i18n.get('Learning / Reviewing'),
      group: i18n.get('Prompts'),
      name: 'useWanakana',
      type: 'checkbox',
      label: i18n.get('Use WanaKana'),
    },
    {
      tab: i18n.get('Learning / Reviewing'),
      group: i18n.get('Prompts'),
      name: 'autocompleteOnTab',
      type: 'checkbox',
      label: i18n.get('Autocomplete a typing prompt by pressing the tab key'),
    },
    {
      tab: i18n.get('Learning / Reviewing'),
      group: i18n.get('Prompts'),
      name: 'showKanjiAfterCorrect',
      type: 'checkbox',
      label: i18n.get('Show the word in Kanji after a correct answer (no guarantee for correctness of Kanji)'),
    },
    {
      tab: i18n.get('Learning / Reviewing'),
      group: i18n.get('Prompts'),
      name: 'customLearnables',
      type: 'checkbox',
      label: i18n.get('Enable editing of the prompt label (only client sided)'),
    },
    {
      tab: i18n.get('Learning / Reviewing'),
      group: i18n.get('Prompts'),
      name: 'noOnscreenKeyboard',
      type: 'checkbox',
      label: i18n.get('Disable on screen keyboard'),
    },
    {
      tab: i18n.get('Learning / Reviewing'),
      group: i18n.get('Prompts'),
      name: 'noAutoAccept',
      type: 'checkbox',
      label: i18n.get('Disable auto-accept'),
    },
    {
      tab: i18n.get('Learning / Reviewing'),
      group: i18n.get('Timer'),
      name: 'alwaysPauseTimer',
      type: 'checkbox',
      label: i18n.get('Always pause the timer'),
    },
    {
      tab: i18n.get('Learning / Reviewing'),
      group: i18n.get('Timer'),
      name: 'preventUnpausing',
      type: 'checkbox',
      label: i18n.get('Prevent Memrise from unpausing the timer (highly recommended)'),
    },
    {
      tab: i18n.get('Learning / Reviewing'),
      group: i18n.get('Timer'),
      name: 'timerClickToggle',
      type: 'checkbox',
      label: i18n.get('Toggle the timer state by clicking on it'),
    },
  ],
};
